In [1]:
import os
os.listdir()

['supermarkets.json',
 'supermarkets-commas.txt',
 '.ipynb_checkpoints',
 'Untitled.ipynb',
 'supermarkets.csv',
 'supermarkets-semi-colons.txt',
 'supermarkets.xlsx']

In [2]:
from geopy.geocoders import Nominatim

In [5]:
import pandas

In [6]:
df1=pandas.read_csv("supermarkets.csv")

In [7]:
df1

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [12]:
df2=pandas.read_json("supermarkets.json")
df2.set_index("ID")

Address           City Country  Employees         Name  \
ID                                                                   
1      3666 21st St  San Francisco     USA          8      Madeira   
2    735 Dolores St  San Francisco     USA         15  Bready Shop   
3       332 Hill St  San Francisco     USA         25  Super River   
4      3995 23rd St  San Francisco     USA         10   Ben's Shop   
5   1056 Sanchez St  San Francisco     USA         12      Sanchez   
6   551 Alvarado St  San Francisco     USA         20   Richvalley   

               State  
ID                    
1           CA 94114  
2           CA 94119  
3   California 94114  
4           CA 94114  
5         California  
6           CA 94114

In [11]:
df2

Address           City Country  Employees  ID         Name  \
0     3666 21st St  San Francisco     USA          8   1      Madeira   
1   735 Dolores St  San Francisco     USA         15   2  Bready Shop   
2      332 Hill St  San Francisco     USA         25   3  Super River   
3     3995 23rd St  San Francisco     USA         10   4   Ben's Shop   
4  1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
5  551 Alvarado St  San Francisco     USA         20   6   Richvalley   

              State  
0          CA 94114  
1          CA 94119  
2  California 94114  
3          CA 94114  
4        California  
5          CA 94114

In [13]:
df7=pandas.read_json("supermarkets.json")
df7.loc?

In [2]:
import geopy
dir(geopy)

['ArcGIS',
 'AzureMaps',
 'Baidu',
 'Bing',
 'DataBC',
 'GeoNames',
 'GeocodeEarth',
 'GeocodeFarm',
 'GoogleV3',
 'Here',
 'IGNFrance',
 'LiveAddress',
 'Location',
 'Nominatim',
 'OpenCage',
 'OpenMapQuest',
 'Pelias',
 'Photon',
 'PickPoint',
 'Point',
 'TomTom',
 'What3Words',
 'Yandex',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'compat',
 'exc',
 'format',
 'geocoders',
 'get_geocoder_for_service',
 'location',
 'point',
 'units',
 'util']

In [3]:
nom = Nominatim(scheme="http")

In [4]:
nom.geocode("3995 23rd St, San Francisco, CA 94114")

Location(3995, 23rd Street, Noe Valley, SF, California, 94114, United States of America, (37.7529648, -122.4317141, 0.0))

In [11]:
import pandas
df=pandas.read_csv("supermarkets.csv")
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [13]:
df["Address"]=df["Address"]+", "+df["City"] + ", " + df["State"] + ", " + df["Country"]
df["Coordinates"]=df["Address"].apply(nom.geocode)


In [18]:
df.Coordinates[0].latitude

37.756488877551

In [27]:
df["Latitude"]=df["Coordinates"].apply(lambda x: x.latitude if x != None else None)
df["Longitude"]=df["Coordinates"].apply(lambda x: x.longitude if x != None else None)
df

ID                                            Address           City  \
0   1  3666 21st St, San Francisco, CA 94114, USA, Sa...  San Francisco   
1   2  735 Dolores St, San Francisco, CA 94119, USA, ...  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, ...  San Francisco   
3   4  3995 23rd St, San Francisco, CA 94114, USA, Sa...  San Francisco   
4   5  1056 Sanchez St, San Francisco, California, US...  San Francisco   
5   6  551 Alvarado St, San Francisco, CA 94114, USA,...  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates   Latitude   Longitude  
0  (3666, 21st Street, Noe Valley, SF, California...  37.756489 -122.429343  
1                                               None        NaN         NaN  
2  (332, Hill Street, Noe Valley, SF, California,...  37.755725 -122.428601  
3  (3995, 23rd Street, Noe Valley, SF, California...  37.752965 -122.431714  
4  (1056, Sanchez Street, Noe Valley, SF, Califor...  37.752146 -122.429815  
5  (551, Alvarado Street, Noe Valley, SF, Califor...  37.753673 -122.433220

In [30]:
import numpy
n=numpy.arange(27)
n


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [31]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [33]:
import cv2
im_g=cv2.imread("smallgray.png", 1)
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)